#!/bin/bash
#SBATCH -t 2:00:00
####SBATCH -t 3-00:00:00
####SBATCH -t 10:00:00
####SBATCH -N 1
#SBATCH -N 1
####SBATCH -p short
####SBATCH -p gpu_short
####SBATCH -p gpu

# To make sure all folders and files within the project space are created with write permission for the group:
umask g+w
cd
#cd microhh/cases/moser600/simulation2
cd /home/robinst/microhh/cases/moser600/git_repository/Neural\ Network/predictions_real_data_MLP10

#Load modules new environment
module purge
module load surf-devel
module load 2019
module load intel/2018b
module load netCDF/4.6.1-intel-2018b
module load netCDF-C++4/4.3.0-intel-2018b
module load CMake/3.12.1-GCCcore-7.3.0
module load cuDNN/7.6.3-CUDA-10.0.130
module load FFTW/3.3.8-intel-2018b
module load Doxygen/1.8.14-GCCcore-7.3.0

##Load modules old environment
#module purge
##module load eb
#module load surfsara
#module load CMake/3.7.2-intel-2016b
##module load cuDNN/7.0.5-CUDA-9.0.176
#module load netCDF/4.4.1.1-intel-2016b
#module load netCDF-C++4/4.3.0-intel-2016b
#module load FFTW/3.3.5-intel-2016b
#module load Doxygen/1.8.11-intel-2016b
##module load Python/3.6.1-intel-2016b Already loaded in virtual environment

export LD_LIBRARY_PATH=$SURFSARA_LIBRARY_PATH:$LD_LIBRARY_PATH #Make sure shared Python libraries can be found

#module purge
#module load eb
#module load surfsara
#module load CMake/3.9.5-GCCcore-6.4.0
#module load cuDNN/7.0.5-CUDA-9.0.176
#module load netCDF/4.5.0-foss-2017b
#module load netCDF-C++4/4.3.0-foss-2017b
#module load Doxygen/1.8.13-GCCcore-6.4.0
#module unload ScaLAPACK/2.0.2-gompi-2017b-OpenBLAS-0.2.20

source ~/virtualenv/firstCNN_intel_CPU/bin/activate

#python3 CNN1_estimator.py > output_CNN1_estimator.txt
#srun python3 CNN1_estimator.py > output_CNN1_estimator.txt


#Make CNN/Smag predictions and reconstruct fields
python3 -u ../read_CNNsmagpredictions.py --prediction_file '/home/robinst/microhh/cases/moser600/git_repository/CNN_checkpoints/real_data_MLP10/MLP_predictions.nc' --smagorinsky_file '/projects/1/flowsim/simulation1/lesscoarse/smagorinsky_fluxes.nc' --training_file '/projects/1/flowsim/simulation1/lesscoarse/training_data.nc' --stats_file '/projects/1/flowsim/simulation1/lesscoarse/means_stdevs_allfields.nc' --reconstruct_fields --make_plots

#ssh -o StrictHostKeyChecking=no -f -N -p 22 -R $PORT:localhost:$PORT int3-bb.cartesius.surfsara.nl
#XDG_RUNTIME_DIR=""
#tensorboard --logdir=/projects/1/flowsim/simulation1/CNN_checkpoints --port=$PORT
##On LOCAL terminal: ssh -N -L40600:localhost:40600 robinst@int3-bb.cartesius.surfsara.nl.
