#!/bin/bash
####SBATCH -t 1:00:00
#SBATCH -t 1-00:00:00
####SBATCH -t 10:00:00
####SBATCH -N 1
#SBATCH -N 3 --ntasks-per-node=1 -c 24
#####SBATCH -p short
####SBATCH -p gpu_short
####SBATCH -p gpu

# To make sure all folders and files within the project space are created with write permission for the group:
umask g+w

PORT=40600

cd
#cd microhh/cases/moser600/simulation2
cd /projects/1/flowsim/simulation1/lesscoarse


#Load modules new environment
module purge
module load surf-devel
module load 2019
module load intel/2018b
module load netCDF/4.6.1-intel-2018b
module load netCDF-C++4/4.3.0-intel-2018b
module load CMake/3.12.1-GCCcore-7.3.0
module load cuDNN/7.6.3-CUDA-10.0.130
module load FFTW/3.3.8-intel-2018b
module load Doxygen/1.8.14-GCCcore-7.3.0

#Load modules old environment
module purge
#module load eb
module load surfsara
module load CMake/3.7.2-intel-2016b
#module load cuDNN/7.0.5-CUDA-9.0.176
module load netCDF/4.4.1.1-intel-2016b
module load netCDF-C++4/4.3.0-intel-2016b
module load FFTW/3.3.5-intel-2016b
module load Doxygen/1.8.11-intel-2016b
#module load Python/3.6.1-intel-2016b Already loaded in virtual environment

export LD_LIBRARY_PATH=$SURFSARA_LIBRARY_PATH:$LD_LIBRARY_PATH #Make sure shared libraries can be found

#module purge
#module load eb
#module load surfsara
#module load CMake/3.9.5-GCCcore-6.4.0
#module load cuDNN/7.0.5-CUDA-9.0.176
#module load netCDF/4.5.0-foss-2017b
#module load netCDF-C++4/4.3.0-foss-2017b
#module load Doxygen/1.8.13-GCCcore-6.4.0
#module unload ScaLAPACK/2.0.2-gompi-2017b-OpenBLAS-0.2.20

## >>> conda initialize >>>
## !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/home/robinst/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/home/robinst/miniconda3/etc/profile.d/conda.sh" ]; then
#        . "/home/robinst/miniconda3/etc/profile.d/conda.sh"
#    else
#        export PATH="/home/robinst/miniconda3/bin:$PATH"
#    fi
#fi
#unset __conda_setup
## <<< conda initialize <<<
#
#conda activate tf_cpu_horovod
source ~/virtualenv/firstCNN_intel_CPU/bin/activate

#python3 CNN1_estimator.py > output_CNN1_estimator.txt
#srun python3 CNN1_estimator.py > output_CNN1_estimator.txt

#Enable Horovod timeline
#export HOROVOD_TIMELINE='/home/robinst/microhh/cases/moser600/git_repository/CNN_checkpoints/real_data_CNN14/horovod.json'

srun python3 /home/robinst/microhh/cases/moser600/git_repository/Neural\ Network/CNN1_estimator.py --input_dir '/projects/1/flowsim/simulation1/lesscoarse/' --checkpoint_dir '/home/robinst/microhh/cases/moser600/git_repository/CNN_checkpoints/real_data_CNN19' --stored_means_stdevs_filepath '/projects/1/flowsim/simulation1/lesscoarse/means_stdevs_allfields.nc' --num_steps 500000 --batch_size 1000 --checkpoint_steps 10000 --benchmark

#ssh -o StrictHostKeyChecking=no -f -N -p 22 -R $PORT:localhost:$PORT int3-bb.cartesius.surfsara.nl
#XDG_RUNTIME_DIR=""
#tensorboard --logdir=/projects/1/flowsim/simulation1/CNN_checkpoints --port=$PORT
##On LOCAL terminal: ssh -N -L40600:localhost:40600 robinst@int3-bb.cartesius.surfsara.nl.
